export { default as HomeView } from './home.vue'
export { default as UserView } from './user.vue'
export { default as RoleView } from './role.vue'
export { default as LoginView } from './login.vue'
export { default as WarehouseView } from './warehouse.vue'
export { default as GoodsTypeView } from './goods-type.vue'
export { default as GoodsView } from './goods.vue'
export { default as RegisterView } from './register.vue'
